remote_theme: pages-themes/slate@v0.2.0
plugins:
  - jekyll-remote-theme
  - jekyll-readme-index
  - jekyll-redirect-from
title: '<img src="https://www.conversion.co.jp/wp-content/uploads/2021/11/cv-logo.png" alt="Conversion Co., Ltd." style="max-width: 100%;" />'
description: Public contents of Conversion on GitHub
show_downloads: false
google_analytics: G-QMEEH3BDES
